services:
  database:
    image: postgres:16.2-alpine3.19
    container_name: "backendagromonitoramento"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: agromonitoramento
    volumes:
      - 'db:/var/lib/postgresql/data'

volumes:
  db:
